#ifndef CONTEMPORARY_GLOBAL_H
#define CONTEMPORARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTEMPORARY_LIBRARY)
#  define CONTEMPORARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONTEMPORARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTEMPORARY_GLOBAL_H
